# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=200)),
                ('handy1', models.CharField(max_length=200)),
                ('email1', models.CharField(max_length=200)),
                ('name2', models.CharField(max_length=200)),
                ('handy2', models.CharField(max_length=200)),
                ('email2', models.CharField(max_length=200)),
                ('plz', models.IntegerField(default=0)),
                ('street', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=2000)),
                ('found_coords', models.BooleanField(default=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
    ]
