# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='newsletter1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='household',
            name='newsletter2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='household',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='household',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
