# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20170510_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='signup_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
