# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20170510_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Cluster'),
        ),
    ]
