# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20170516_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='color',
        ),
    ]
