# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20170522_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='firstVisit',
            new_name='first_visit',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='secondVisit',
            new_name='second_visit',
        ),
        migrations.RenameField(
            model_name='household',
            old_name='thirdVisit',
            new_name='third_visit',
        ),
    ]
