# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20170522_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitinggroup',
            old_name='visitingGroupNum',
            new_name='visiting_group_num',
        ),
    ]
