# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20170523_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='plz',
            field=models.IntegerField(choices=[(76131, '76131 (Innen- & Oststadt)'), (76133, '76133 (Innen-, Nord-, West-, Südweststadt)'), (76135, '76135 (West-, Südweststadt, Beiertheim-Bulach)'), (76137, '76137 (Südstadt, Südweststadt)')], default=76133),
        ),
    ]
