# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20170525_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='bic',
            field=models.CharField(default='123', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='iban',
            field=models.CharField(default='23123', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='kontoinhaber',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='personal_payment',
            field=models.BooleanField(default=False),
        ),
    ]
