# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20170528_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='gpsstreet',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
    ]
