# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_mandatsreferenzcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='mandatsreferenz',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='bic',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='iban',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='kontoinhaber',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
