# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_auto_20170607_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='bic',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='household',
            name='handy2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='household',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='household',
            name='kontoinhaber',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='household',
            name='mandatsreferenz',
            field=models.CharField(blank=True, default='', max_length=35),
            preserve_default=False,
        ),
    ]
