# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_auto_20170607_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='handy2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='household',
            name='note',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
