# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_auto_20170612_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='kontoinhaber_city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='household',
            name='kontoinhaber_street',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
