# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_auto_20170612_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.Cluster'),
        ),
        migrations.AlterField(
            model_name='household',
            name='first_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household1', to='frontend.VisitingGroup'),
        ),
        migrations.AlterField(
            model_name='household',
            name='second_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household2', to='frontend.VisitingGroup'),
        ),
        migrations.AlterField(
            model_name='household',
            name='third_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household3', to='frontend.VisitingGroup'),
        ),
    ]
