# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_auto_20170615_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='puzzle',
            field=models.IntegerField(choices=[(0, 'Null'), (91, 'Vorspeise 1.G, Hauptspeise A.1, Nachspeise N.1'), (92, 'Vorspeise 1.1, Hauptspeise B.G, Nachspeise N.1'), (93, 'Vorspeise 1.2, Hauptspeise C.G, Nachspeise N.1'), (94, 'Vorspeise 2.1, Hauptspeise A.G, Nachspeise N.2'), (95, 'Vorspeise 2.G, Hauptspeise B.1, Nachspeise N.2'), (96, 'Vorspeise 2.2, Hauptspeise C.1, Nachspeise N.G'), (97, 'Vorspeise 3.G, Hauptspeise A.2, Nachspeise N.2'), (98, 'Vorspeise 3.1, Hauptspeise B.2, Nachspeise N.G'), (99, 'Vorspeise 3.2, Hauptspeise C.2, Nachspeise N.G'), (1201, 'Vorspeise 1.G, Hauptspeise A.1, Nachspeise N.1'), (1202, 'Vorspeise 1.1, Hauptspeise B.G, Nachspeise N.1'), (1203, 'Vorspeise 1.2, Hauptspeise B.G, Nachspeise N.1'), (1204, 'Vorspeise 2.1, Hauptspeise A.G, Nachspeise N.2'), (1205, 'Vorspeise 2.G, Hauptspeise B.1, Nachspeise N.2'), (1206, 'Vorspeise 2.2, Hauptspeise C.1, Nachspeise N.G'), (1207, 'Vorspeise 3.G, Hauptspeise B.2, Nachspeise N.2'), (1208, 'Vorspeise 3.1, Hauptspeise B.2, Nachspeise N.G'), (1209, 'Vorspeise 3.2, Hauptspeise C.2, Nachspeise N.G'), (1210, 'Vorspeise 2.G, Hauptspeise A.2, Nachspeise N.1'), (1211, 'Vorspeise 2.1, Hauptspeise B.1, Nachspeise N.G'), (1212, 'Vorspeise 2.2, Hauptspeise C.G, Nachspeise N.2')], default=0),
        ),
    ]
