# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_household_puzzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='is12',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='household',
            name='puzzle',
            field=models.IntegerField(choices=[(0, 'Null'), (91, '9.1 Vorspeise 1.G, Hauptspeise A.1, Nachspeise N.1'), (92, '9.2 Vorspeise 1.1, Hauptspeise B.G, Nachspeise N.1'), (93, '9.3 Vorspeise 1.2, Hauptspeise C.G, Nachspeise N.1'), (94, '9.4 Vorspeise 2.1, Hauptspeise A.G, Nachspeise N.2'), (95, '9.5 Vorspeise 2.G, Hauptspeise B.1, Nachspeise N.2'), (96, '9.6 Vorspeise 2.2, Hauptspeise C.1, Nachspeise N.G'), (97, '9.7 Vorspeise 3.G, Hauptspeise A.2, Nachspeise N.2'), (98, '9.8 Vorspeise 3.1, Hauptspeise B.2, Nachspeise N.G'), (99, '9.9 Vorspeise 3.2, Hauptspeise C.2, Nachspeise N.G'), (1201, '12.01 Vorspeise 1.G, Hauptspeise A.1, Nachspeise N.1'), (1202, '12.02 Vorspeise 1.1, Hauptspeise B.G, Nachspeise N.1'), (1203, '12.03 Vorspeise 1.2, Hauptspeise B.G, Nachspeise N.1'), (1204, '12.04 Vorspeise 2.1, Hauptspeise A.G, Nachspeise N.2'), (1205, '12.05 Vorspeise 2.G, Hauptspeise B.1, Nachspeise N.2'), (1206, '12.06 Vorspeise 2.2, Hauptspeise C.1, Nachspeise N.G'), (1207, '12.07 Vorspeise 3.G, Hauptspeise B.2, Nachspeise N.2'), (1208, '12.08 Vorspeise 3.1, Hauptspeise B.2, Nachspeise N.G'), (1209, '12.09 Vorspeise 3.2, Hauptspeise C.2, Nachspeise N.G'), (1210, '12.10 Vorspeise 2.G, Hauptspeise A.2, Nachspeise N.1'), (1211, '12.11 Vorspeise 2.1, Hauptspeise B.1, Nachspeise N.G'), (1212, '12.12 Vorspeise 2.2, Hauptspeise C.G, Nachspeise N.2')], default=0),
        ),
    ]
