# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_auto_20170630_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
        migrations.AddField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='frontend.Post'),
            preserve_default=False,
        ),
    ]
