# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_auto_20170630_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='media/couch/posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
