# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-11 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_auto_20170701_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='plz',
            field=models.IntegerField(choices=[(53111, '53111 Bonn-Zentrum/-Castell/Nordstadt'), (53113, '53113 Bonn-Zentrum/Gronau/Kessenich/Poppelsdorf/Südstadt'), (53115, '53115 Bonn-Zentrum/Kessenich/Poppelsdorf/Südstadt/Venusberg/Weststadt'), (53117, '53117 Auerberg /Bonn-Castell/ Buschdorf/Graurheindorf'), (53119, '53119 Auerberg/Nordstadt/Tannenbusch'), (53121, '53121 Dransdorf'), (53123, '53123 Duisdorf/Lengsdorf/Lessenich/Meßdorf'), (53125, '53125 Brüser Berg/Duisdorf/Ippendorf/Röttgen'), (53127, '53127 Friesdorf/Poppelsdorf/Venusberg/ Ippendorf/Lengsdorf'), (53129, '53129 Dottendorf/Kessenich/Poppelsdorf'), (53179, '53179 Mehlem'), (53225, '53225 Beuel Mitte/Geislar'), (53227, '53227 Beuel-Mitte/-Ost'), (53229, '53229 Beuel-Ost')], default=76133),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='couch/posts'),
        ),
    ]
